import {
  Briefcase,
  Dumbbell,
  BookOpen,
  HeartPulse,
  Users,
  Home,
  UtensilsCrossed,
  Sparkles,
  Target,
  Activity,
  Car,
  Wallet,
  Palette,
  PawPrint,
  ShoppingCart,
  Gamepad2,
  GlassWater,
  StretchHorizontal,
  Coffee,
  NotebookPen,
  ShowerHead,
  Brain,
  PhoneOff,
  CloudSun,
  Footprints,
  BedDouble,
  AlarmClock,
  BookOpenText,
  BookMarked,
  Repeat2,
  UserRound,
  Cat,
  Dog,
  Bird,
  Rabbit,
  Turtle,
  Squirrel,
  Fish,
  Star,
  Heart,
  Leaf,
  Sun,
  Moon,
  Flame,
  Circle,
  type LucideIcon,
} from 'lucide-react'

export const iconRegistry: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  dumbbell: Dumbbell,
  book: BookOpen,
  'heart-pulse': HeartPulse,
  users: Users,
  home: Home,
  utensils: UtensilsCrossed,
  sparkles: Sparkles,
  target: Target,
  activity: Activity,
  car: Car,
  wallet: Wallet,
  palette: Palette,
  paw: PawPrint,
  cart: ShoppingCart,
  gamepad: Gamepad2,

  'glass-water': GlassWater,
  stretch: StretchHorizontal,
  coffee: Coffee,
  'notebook-pen': NotebookPen,
  shower: ShowerHead,
  brain: Brain,
  'phone-off': PhoneOff,
  'cloud-sun': CloudSun,
  footprints: Footprints,
  bed: BedDouble,
  'alarm-clock': AlarmClock,
  'book-text': BookOpenText,
  quran: BookMarked,
  dhikr: Repeat2,

  user: UserRound,
  cat: Cat,
  dog: Dog,
  bird: Bird,
  rabbit: Rabbit,
  turtle: Turtle,
  squirrel: Squirrel,
  fish: Fish,
  star: Star,
  heart: Heart,
  leaf: Leaf,
  sun: Sun,
  moon: Moon,
  flame: Flame,
}

export const categoryIconChoices = [
  'briefcase',
  'dumbbell',
  'book',
  'heart-pulse',
  'users',
  'home',
  'utensils',
  'sparkles',
  'target',
  'activity',
  'car',
  'wallet',
  'palette',
  'paw',
  'cart',
  'gamepad',
  'quran',
  'dhikr',
]

export const routineIconChoices = [
  'glass-water',
  'stretch',
  'coffee',
  'notebook-pen',
  'shower',
  'brain',
  'phone-off',
  'cloud-sun',
  'footprints',
  'bed',
  'alarm-clock',
  'book-text',
  'sparkles',
  'sun',
  'moon',
  'quran',
  'dhikr',
]

export const avatarIconChoices = [
  'user',
  'cat',
  'dog',
  'bird',
  'rabbit',
  'turtle',
  'squirrel',
  'fish',
  'star',
  'heart',
  'leaf',
  'sun',
  'moon',
  'flame',
]

export function Icon({
  name,
  size = 18,
  className,
  strokeWidth = 2,
  style,
}: {
  name?: string
  size?: number
  className?: string
  strokeWidth?: number
  style?: React.CSSProperties
}) {
  const Cmp = (name && iconRegistry[name]) || Circle
  return <Cmp size={size} className={className} strokeWidth={strokeWidth} style={style} />
}
